reddit_credentials:
  username: "fakebot1"
  password: "invalidht4wd50gk"
  client_id: "revokedpDQy3xZ"
  client_secret: "revokedoqsMk5nHCJTHLrwgvHpr"

subreddit: "example_subreddit"
word_count_threshold: 300
days: 7

# Whether to include comment body in submission or not.
include_body: True